<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-02-14T11:01:52 IST" name="Suite" finished-at="2024-02-14T11:01:52 IST" duration-ms="72">
    <groups>
      <group name="smoke">
        <method signature="thirdTests.method3()[pri:0, instance:testng.tests.thirdTests@20deea7f]" name="method3" class="testng.tests.thirdTests"/>
      </group> <!-- smoke -->
    </groups>
    <test started-at="2024-02-14T11:01:52 IST" name="parameteres" finished-at="2024-02-14T11:01:52 IST" duration-ms="72">
      <class name="testng.tests.thirdTests">
        <test-method is-config="true" signature="bTest()[pri:0, instance:testng.tests.thirdTests@20deea7f]" started-at="2024-02-14T11:01:52 IST" name="bTest" finished-at="2024-02-14T11:01:52 IST" duration-ms="12" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- bTest -->
        <test-method is-config="true" signature="bMethod()[pri:0, instance:testng.tests.thirdTests@20deea7f]" started-at="2024-02-14T11:01:52 IST" name="bMethod" finished-at="2024-02-14T11:01:52 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- bMethod -->
        <test-method signature="method3()[pri:0, instance:testng.tests.thirdTests@20deea7f]" started-at="2024-02-14T11:01:52 IST" name="method3" finished-at="2024-02-14T11:01:52 IST" duration-ms="1" status="FAIL">
          <exception class="java.lang.ArithmeticException">
            <message>
              <![CDATA[/ by zero]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.ArithmeticException: / by zero
at testng.tests.thirdTests.method3(thirdTests.java:33)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.ArithmeticException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- method3 -->
        <test-method is-config="true" signature="AMethod()[pri:0, instance:testng.tests.thirdTests@20deea7f]" started-at="2024-02-14T11:01:52 IST" name="AMethod" finished-at="2024-02-14T11:01:52 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AMethod -->
        <test-method is-config="true" signature="ATest()[pri:0, instance:testng.tests.thirdTests@20deea7f]" started-at="2024-02-14T11:01:52 IST" name="ATest" finished-at="2024-02-14T11:01:52 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ATest -->
      </class> <!-- testng.tests.thirdTests -->
      <class name="testng.tests.parameters">
        <test-method signature="Login(java.lang.String,java.lang.String)[pri:0, instance:testng.tests.parameters@63355449]" started-at="2024-02-14T11:01:52 IST" name="Login" finished-at="2024-02-14T11:01:52 IST" duration-ms="2" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[admin]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[admin123]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login -->
      </class> <!-- testng.tests.parameters -->
    </test> <!-- parameteres -->
  </suite> <!-- Suite -->
</testng-results>
